import React from "react"
import { BasicButtonContained } from "primitives"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BasicButtonContained,
  "https://www.figma.com/design/2TnwsFNeqz0UQXhdDlFeuy/Component-Mobile?node-id=715-3964&t=o8azNLewD8DTQclB-4",
  {
    props: {
      ic: figma.instance("ic"),
      text: figma.string("text"),
      type: figma.enum("type", {
        primary: "primary",
        auxillary: "auxillary",
        white: "white",
      }),
      size: figma.enum("size", {
        large: "large",
        middle: "middle",
        small: "small",
      }),
      state: figma.enum("state", {
        normal: "normal",
        press: "press",
        disable: "disable",
      }),
      icon: figma.boolean("icon"),
    },
    example: (props) => (
      <BasicButtonContained
        type={props.type}
        size={props.size}
        state={props.state}
        icon={props.icon}
        text={props.text}
        ic={props.ic}
      />
    ),
  },
)
